### ISSUE TITLE
Re-using `hub` token?

### ISSUE THREAD

**Issue by bhipple** [magit/forge#261]
I'm having a lot of trouble getting the authentication file setup for GitHub, probably because my account has 2FA auth enabled (?).  I'm attempting to follow the docs and create an `~/.authinfo` token manually, and while doing so I was wondering if it'd be possible to support just re-using [hub](https://github.com/github/hub) tokens if they exist?

Many users who are using GitHub will already have [hub](https://github.com/github/hub) setup, which creates a token itself like this:

```yaml
# ~/.config/hub
github.com:
- user: bhipple
  oauth_token: <redacted>
  protocol: https
```
